#Spring Application Name
spring:
  application:
    name: Zuul-Server

#Server Port
server:
  port: 8765

#Eureka Instance ID
eureka:
  client:
      registerWithEureka: false
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

#Ribbon Activation
ribbon:
  eureka:
    enabled: true